In [1]:
using MLDataUtils
using MLDatasets       # mnist

# load mnist from MLDatasets
trainX, trainY = MNIST.traindata()
testX,  testY  = MNIST.testdata();


In [2]:
getobs((trainX, trainY), 30)[1]

28×28 Array{N0f8,2} with eltype FixedPointNumbers.N0f8:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.184  0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.957  0.118  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.682  0.055  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0    0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0 

In [3]:
trY, teY = stratifiedobs((trainY), at = 0.7);


LoadError: MethodError: no method matching stratifiedobs(::Vector{Int64}; at=0.7)
Closest candidates are:
  stratifiedobs(::Any; p, shuffle, obsdim, rng) at /home/ciro/.julia/packages/MLDataPattern/KlSmO/src/stratifiedobs.jl:206 got unsupported keyword argument "at"
  stratifiedobs(::Any, ::AbstractFloat, ::Any...) at /home/ciro/.julia/packages/MLDataPattern/KlSmO/src/stratifiedobs.jl:214 got unsupported keyword argument "at"
  stratifiedobs(::Any, ::Tuple{Vararg{AbstractFloat, N}}, ::Any...) where N at /home/ciro/.julia/packages/MLDataPattern/KlSmO/src/stratifiedobs.jl:218 got unsupported keyword argument "at"
  ...

In [21]:
A=[1 2;3 4;5 6]
display(A)
display(length(A))
reshape(A,(length(A),))'

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

6

1×6 adjoint(::Vector{Int64}) with eltype Int64:
 1  3  5  2  4  6

In [31]:
M = trainX[:,:,1]
reshape(M,(length(M),))


784-element Array{N0f8,1} with eltype FixedPointNumbers.N0f8:
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 ⋮
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8
 0.0N0f8

In [41]:
[   reshape( trainX[:,:,i],(784,) )   for i in 1:40000]

40000-element Vector{Vector{FixedPointNumbers.N0f8}}:
 [0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8  …  0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8]
 [0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8  …  0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8]
 [0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8  …  0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8]
 [0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8  …  0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8]
 [0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8  …  0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8, 0.0N0f8]
 [0.0N0f8, 0.0N0f8, 0